apiVersion: v1
kind: Service
metadata: 
  name: flask-nodeport
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31001
  selector:
    app: flaskapp
---
apiVersion: v1
kind: Pod
metadata:

  name: flaskapp
  labels: 
    app: flaskapp

spec:

  volumes:

  - name: appvol
    hostPath: 
      # path: /home/alex/github/flaskapp/app
      path: /home/alex/kuber/app
    
  - name: dbvol
    hostPath:
      path: /home/alex/kuber/mysql
      # path: /home/alex/github/flaskapp/mysql

  containers:

    - image: ababa777/flaskapp
      name: app
      volumeMounts:
      - name: appvol
        mountPath: /app
      command: ['python3 /app/app.py runserver --host 0.0.0.0 -d -r']
      ports:
      - containerPort: 5000
      envFrom:
      - configMapRef:
          name: flask-configmap

    - image: jamielsharief/mysql:latest
      name: db
      volumeMounts:
      - name: dbvol
        mountPath: /var/lib/mysql
      ports:
      - containerPort: 3306
      envFrom:
      - configMapRef:
          name: flask-configmap